name: basic
description: A basic game built in Flutter.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^5.2.0
  cupertino_icons: ^1.0.6
  go_router: ^13.0.0
  logging: ^1.2.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  image: ^4.1.6
  flutter_spinkit: ^5.2.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  test: ^1.24.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/avatars/transparent/
    - assets/images/misc/
    - assets/images/avatars/
    - assets/images/
    - assets/music/
    - assets/sfx/
    - assets/images/bg/

  fonts:
    - family:  CustomFlutterIcon
      fonts:
        - asset: assets/fonts/CustomFlutterIcon/CustomFlutterIcon.ttf
    - family: Chelsea
      fonts:
        - asset: assets\fonts\Chelsea\Chelsea.ttf
    - family: LTC
      fonts:
        - asset: assets/fonts/LTC/ltckenneregpro.woff.ttf
    - family : BLACKCHA
      fonts:
        - asset: assets\fonts\BLACKCHA\BLKCHCRY.TTF
    # - family: Permanent Marker
    #   fonts:
    #     - asset: assets/fonts/Permanent_Marker/PermanentMarker-Regular.ttf
    # - family: Great Victorian
    #   fonts:
    #     - asset: assets\fonts\Great_Victorian\GreatVictorian-Standard.otf
    #     - asset: assets\fonts\Great_Victorian\GreatVictorian-Swashed.otf
    #     - asset: assets\fonts\Great_Victorian\GreatVictorian-SwashedSC.otf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/icon-adaptive-foreground.png"
